### PR TITLE
Clear `list` states (i.e. delete their contents), not reassign the default `[]`

### LINKED ISSUE #2492: `list` states leak (`Tensor`) memory
## 🐛 Bug

Hello!

I've recently tracked a CPU (possibly GPU also) memory leak to `list[Tensor]` states. For example:
```
import torch
from torchmetrics import Metric

class DummyListMetric(Metric):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.add_state("x", default=[])

    def update(self, x=None):
        x = torch.tensor(1) if x is None else x
        self.x.append(x)
```

When (the parent) `Metric.reset()` is called, `self.x` is simply overwritten with an empty list [1]. Unfortunately, this doesn't guarantee that the contents of `self.x` are deleted, meaning `Tensor` elements are not always correctly freed

After some investigation, I found my custom metrics (subclasses of`Metric`) didn't cause my (work) system to run out of memory if I added the following overload:
```
def reset(self):
    for attr, default in self._defaults.items():
        if isinstance(default, list):
            getattr(self, attr).clear()

    return super().reset()
```

The same fix can be applied directly inside `torchmetrics` with a single line change, modifying [2] to:
```
getattr(self, attr).clear()
```

Looking at other open issues, this issue might be related to #2481 (which also references `list` states). I'd be very happy to open a PR if the above sounds reasonable. Many thanks!

- [1] https://github.com/Lightning-AI/torchmetrics/blob/master/src/torchmetrics/metric.py#L673
- [2] https://github.com/Lightning-AI/torchmetrics/blob/master/src/torchmetrics/metric.py#L684

### Environment

- TorchMetrics version: 1.3.2
- Python & PyTorch Version: 3.11.8 & 2.2.1

### PR DESCRIPTION
**Pull request by dominicgkerr**
Rather than overwriting `list` states (with `[]`), call `.clear()` to correctly (more robustly?) delete/free `Tensor` elements. Previous behaviour results in CPU (possibly GPU also) memory leak

## What does this PR do?

Fixes #2492 (maybe #2481 also)

<details>
  <summary>Before submitting</summary>

- [X] Was this **discussed** via a Github issue? (no need for typos and docs improvements)
- [X] Did you read the [contributor guideline](https://github.com/Lightning-AI/torchmetrics/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [ ] ~Did you make sure to **update the docs**?~
- [ ] Did you write any new **necessary tests**?

</details>

<details>
  <summary>PR review</summary>

Anyone in the community is free to review the PR once the tests have passed.
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

</details>

## Did you have fun?

Make sure you had fun coding 🙃

----
📚 Documentation preview 📚: https://torchmetrics--2493.org.readthedocs.build/en/2493/

### CODE REVIEW

**Review by Borda — APPROVED** [review]
nice, can we also have a test to cover this edge-case?

**Comment by dominicgkerr** [comment]
> nice, can we also have a test to cover this edge-case?

Absolutely! Added 1fa7077 to help illustrate the issue (and how the fix helps)

**Review by justusschock — COMMENTED** [review]
Thanks for your PR and that's certainly a great find. 
That being said, I am actually not sure what's the desired behavior here.

I can see good reasons for both ways.

I.e. It might be very confusing for people if they keep a reference to things why this one suddenly empty, whereas with just instantiating a new list we're doing everything correctly on our side and still give the user the possibility to retain a reference to the old state if they wish to. So this would only lead to a memory leak in user code, not on our side.

**Comment by dominicgkerr** [comment]
Interesting - I hadn't thought of that scenario being desirable...

I would argue though, the exiting behaviour is certainly unexpected (according to the current documentation). My reading of `.add_state` is that users (intentionally) defer the memory/device management entirely to `Metric`, and wouldn't use it if they needed something more complex (like persistent references.) Similarly, I naturally expect `.reset` to return the `Metric` to its original states, AND to tidy-up any intermediate values calculated by `.update` (which are currently leaked.) 

In my specific use-case, I'm fitting a `LighntningModule` to a very large dataset. I have a setup very similar to [1], except I'm using a custom `Metric` with a `list` state - over the course of a large number of training steps, I consistently see my CPU memory usage increase (as a result of #2492) until the python process crashes.

If you're keen to support the ability to retain references to `Metric` states, would introducing a (say) `free_on_reset: bool` keyword argument to `.add_state` (that conditionally deletes/clears states before reassigning the default value) be preferable? Setting `free_on_reset=True` by could enable the new behaviour by default, while still allowing users to revert to the existing behaviour whn they require something more complex?

- [1] https://lightning.ai/docs/torchmetrics/stable/pages/lightning.html#logging-torchmetrics

**Comment by justusschock** [comment]
I think you have some valid arguments there. Could you just add that to the documentation and refer people to use copy/deepcopy if the want to retain the states?

**Comment by dominicgkerr** [comment]
Brilliant, thanks! I've updated the docstring/documentation - let me know if it needs rewording/expanding/etc... 

Unfortunately I couldn't get `make docs` to build locally (as I couldn't `pip install lai-sphinx-theme`), so just waiting on the CI to double check my formatting is correct

Thanks again

**Comment by Borda** [comment]
@SkafteNicki thoughts?

**Review by justusschock — APPROVED** [review]

**Review by SkafteNicki — APPROVED** [review]

**Comment by Borda** [comment]
@dominicgkerr there are too many failing tests, could you pls have look...

**Comment by dominicgkerr** [comment]
@SkafteNicki Nice (5758977) - was just looking at the `.forward` logic!

**Comment by SkafteNicki** [comment]
@dominicgkerr you are welcome :)
Hopefully all tests should pass now

**Comment by dominicgkerr** [comment]
I think I've got things working (better?) now... @SkafteNicki / [5758977](https://github.com/Lightning-AI/torchmetrics/pull/2493/commits/57589773c28cebd6de20ec5bc76a3c4a0099b1c0) was a huge help (thanks!), as I hadn't spotted the caching behaviour inside `.forward` / `.update` before.

Rather than simply using `deepcopy` (which worked in all but one edge case), I added a `._copy_state_dict` helper method to `.detach().clone()` `Tensor` / `list[Tensor]` states inserted into the cache. Unfortunately this caused `tests/unittests/bases/test_metric.py:test_constant_memory_on_repeat_init` to fail, but I found (in [ef27215](https://github.com/Lightning-AI/torchmetrics/pull/2493/commits/ef2721575cfe5993ceba94c455903f3bf1356831)) that removing the `.clone()` calls, fixed it. But, as the resulting cache might now contain references to `Tensor` values, I was suspicious that it somehow leak memory...

After some digging, I came to the conclusion that `test_constant_memory_on_repeat_init` wasn't actually testing memory leakage during initialisation, but actually ensure repeated `.forward` calls didn't (significantly) increase the metric's memory. As an illustration, moving `x = torch.randn(10000).cuda()` inside the test's `for` loop (where a constant `Tensor` couldn't be automatically referenced by python/pytorch in subsequent calls), actually caused it to fail...

I claim, memory should be allowed to increase here (as users might legitimately want to collect lots of observations during fitting, and combine them inside `.compute`), as long as the allocated memory is eventually freed by `.reset`. I've added a new test (`test_freed_memory_on_reset`) check this. 

I appreciate changing (failing) tests to pass the CI is pretty suspect - hopefully the above explains why I did (let me know if not!)

**Review by stancld — APPROVED** [review]

**Comment by janEbert** [comment]
Should the same be applied here as well?
https://github.com/Lightning-AI/torchmetrics/blob/d528131c8e7f130c65ba62a14e12f15906d488c1/src/torchmetrics/metric.py#L530

**Pull request merged**
