### PR TITLE
lint: resolve B905

### PR DESCRIPTION
**Pull request by matsumotosan**
## What does this PR do?

Resolve B905: zip-without-explicit-strict

<details>
  <summary>Before submitting</summary>

- [x] Was this **discussed/agreed** via a Github issue? (no need for typos and docs improvements)
- [x] Did you read the [contributor guideline](https://github.com/Lightning-AI/torchmetrics/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [x] Did you make sure to **update the docs**?
- [x] Did you write any new **necessary tests**?

</details>

<details>
  <summary>PR review</summary>

Anyone in the community is free to review the PR once the tests have passed.
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

</details>

## Did you have fun?

Make sure you had fun coding 🙃

----
:books: Documentation preview :books:: https://torchmetrics--2154.org.readthedocs.build/en/2154/

### CODE REVIEW

**Comment by SkafteNicki** [comment]
Sadly this is not supported before python 3.10, so we really cannot add this in the next foreseeable future.

**Comment by Borda** [comment]
> Sadly this is not supported before python 3.10, so we really cannot add this in the next foreseeable future.

@matsumotosan sorry for that I made it as todo, did not know it is not feasible :crying_cat_face:

**Review by Borda — APPROVED** [review]

**Comment by Borda** [comment]
@matsumotosan made some adjustments; could you pls check...

**Comment by matsumotosan** [comment]
So there's a case where the length of items in the arguments to zip aren't equal in the call to `_precision_at_recall` in `functional.classification.precision_fixed_recall` (`len(thresholds)` is 4, but `len(precision)` and `len(recall)` are 5).

I haven't had the time to familiarize myself with this function so wanted to see if anyone had any immediate ideas before I go deeper into the code.

**Comment by Borda** [comment]
> So there's a case where the length of items in the arguments to zip aren't equal in the call to `_precision_at_recall` in `functional.classification.precision_fixed_recall` (`len(thresholds)` is 4, but `len(precision)` and `len(recall)` are 5).

this is good finding, @SkafteNicki

**Comment by SkafteNicki** [comment]
> So there's a case where the length of items in the arguments to zip aren't equal in the call to `_precision_at_recall` in `functional.classification.precision_fixed_recall` (`len(thresholds)` is 4, but `len(precision)` and `len(recall)` are 5).
> 
> I haven't had the time to familiarize myself with this function so wanted to see if anyone had any immediate ideas before I go deeper into the code.

It is correct that in most cases thresholds is one value shorter than the corresponding values. That is mostly to be consistent with how scikit learn is doing it. In those cases I guess the argument would need to be `False`

**Pull request merged**
