### PR TITLE
New segmentation metric: Hausdorff Distance

### LINKED ISSUE #1990: Add Hausdorff distance as a new classification metric
## 🚀 Feature

Add Hausdorff distance as a new classification metric.

### Motivation

Hausdorff distance measures how far two subsets of a metric space are from each other. Informally, two sets are close in the Hausdorff distance if every point of either set is close to some end of the other set. The Hausdorff distance is the longest distance you can be forced to travel by an adversary who chooses a point in one of the two sets, from where you then must travel to the other set. In other words, it is the greatest of all the distances from a point in one set to the closest point in the other set. More on: https://en.wikipedia.org/wiki/Hausdorff_distance

### Pitch

Haussdorff distance is an important metric to find the smoothness of the predicted segmentation map. It is widely used for segmenting medical images.

### Alternatives

We can find the following implementations in other libraries.

1. Scikit Image: https://scikit-image.org/docs/stable/api/skimage.metrics.html#skimage.metrics.hausdorff_distance
2. Scipy: https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.distance.directed_hausdorff.html
3. MONAI: https://docs.monai.io/en/latest/_modules/monai/metrics/hausdorff_distance.html

### PR DESCRIPTION
**Pull request by matsumotosan**
## What does this PR do?

Fixes #1990 

<details>
  <summary>Before submitting</summary>

- [x ] Was this **discussed/agreed** via a Github issue? (no need for typos and docs improvements)
- [x] Did you read the [contributor guideline](https://github.com/Lightning-AI/torchmetrics/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [x] Did you make sure to **update the docs**?
- [x] Did you write any new **necessary tests**?

</details>

<details>
  <summary>PR review</summary>

Anyone in the community is free to review the PR once the tests have passed.
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

</details>

## Did you have fun?

Make sure you had fun coding 🙃

----
:books: Documentation preview :books:: https://torchmetrics--2122.org.readthedocs.build/en/2122/

### CODE REVIEW

**Comment by Borda** [comment]
Seems like a big collision. Could you check it or maybe cherry-pick your commits on top of the master?

**Comment by Borda** [comment]
@matsumotosan @SkafteNicki I have rebased it to master to reduce the colliding commits accidentally leaked from the master... could you pls check if I did it correctly?
Moreover, @matsumotosan, what is missing to let it land? :flamingo:

**Comment by Borda** [comment]
hello @matsumotosan, how is it going here, can we help you to land it?

**Comment by Nachiket18** [comment]
I'm interested in contributing for this metric. I know about Hausdorff distance, and I have worked on several other metrics like edit, Jaccard, Jaro Winkler distance.

**Comment by Borda** [comment]
> I'm interested in contributing for this metric. I know about Hausdorff distance, and I have worked on several other metrics like edit, Jaccard, Jaro Winkler distance.

that is great! looking forward to see your PR :flags:

**Comment by Borda** [comment]
@baskrahmer how is it going here? :)

**Comment by baskrahmer** [comment]
> @baskrahmer how is it going here? :)

There is an issue with the tests, related to running with DDP. Could you have a look?

**Review by Borda — APPROVED** [review]

**Review by SkafteNicki — APPROVED** [review]

**Pull request merged**
