### PR TITLE
docs: enable Sphinx nitpicky

### PR DESCRIPTION
**Pull request by Borda**
## What does this PR do?

> [nitpicky](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-nitpicky)
If true, Sphinx will warn about all references where the target cannot be found. Default is False. You can activate this mode temporarily using the [-n](https://www.sphinx-doc.org/en/master/man/sphinx-build.html#cmdoption-sphinx-build-n) command-line switch.

ref: https://github.com/optuna/optuna/issues/4213

<details>
  <summary>Before submitting</summary>

- [ ] Was this **discussed/agreed** via a Github issue? (no need for typos and docs improvements)
- [x] Did you read the [contributor guideline](https://github.com/Lightning-AI/torchmetrics/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [x] Did you make sure to **update the docs**?
- [ ] Did you write any new **necessary tests**?

</details>

<details>
  <summary>PR review</summary>

Anyone in the community is free to review the PR once the tests have passed.
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

</details>

## Did you have fun?

Make sure you had fun coding 🙃

----
:books: Documentation preview :books:: https://torchmetrics--1916.org.readthedocs.build/en/1916/

### CODE REVIEW

**Comment by Borda** [comment]
So not sure how to tell sphinx mapping also, this just built package... :/

**Comment by Borda** [comment]
also these seem to be missing `WARNING: py:class reference target not found: torch.FloatTensor`

**Review by SkafteNicki — APPROVED** [review]

**Review by stancld — APPROVED** [review]

**Comment by Borda** [comment]
Ok, checked some and seems some links are really wrong so need to get fixed...

**Comment by Borda** [comment]
lets wait for #1956 and #1958

**Review by justusschock — APPROVED** [review]

**Comment by Borda** [comment]
THANK YOU @SkafteNicki :purple_heart:

**Pull request merged**
