### PR TITLE
Resolve ANN102

### PR DESCRIPTION
**Pull request by matsumotosan**
## What does this PR do?

Resolve ANN102: missing-type-cls

<details>
  <summary>Before submitting</summary>

- [ ] Was this **discussed/agreed** via a Github issue? (no need for typos and docs improvements)
- [ ] Did you read the [contributor guideline](https://github.com/Lightning-AI/torchmetrics/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [ ] Did you make sure to **update the docs**?
- [ ] Did you write any new **necessary tests**?

</details>

<details>
  <summary>PR review</summary>

Anyone in the community is free to review the PR once the tests have passed.
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

</details>

## Did you have fun?

Make sure you had fun coding 🙃

----
:books: Documentation preview :books:: https://torchmetrics--2149.org.readthedocs.build/en/2149/

### CODE REVIEW

**Review by stancld — DISMISSED** [review]
I'm not sure if we want to add type annotation for `cls`. Personally, I see this rule to be a bit abundant and annoying :D

**Comment by matsumotosan** [comment]
I think I accidentally fixed the wrong linter error. I can close this PR if this isn't a style we want to enforce.

**Comment by justusschock** [comment]
imo that would be fine but I think indexing the builtin type is not supported for every python version so we might want to consider something from the typing package instead

**Comment by stancld** [comment]
> imo that would be fine but I think indexing the builtin type is not supported for every python version so we might want to consider something from the typing package instead

Yes, `typing.Type` should work here. `type` built-in for annotations was added in 3.9/3.10 I think

**Comment by matsumotosan** [comment]
Unit tests for old failed `RuntimeError: CUDA error: no kernel image is available for execution on the...`

**Comment by Borda** [comment]
> Unit tests for old failed `RuntimeError: CUDA error: no kernel image is available for execution on the...`

seems we have some flakes in the system... :/

**Review by SkafteNicki — APPROVED** [review]

**Review by justusschock — APPROVED** [review]

**Comment by Borda** [comment]
@stancld do you still have a request for changes? :rabbit:

**Review by stancld — APPROVED** [review]

**Pull request merged**
